### ISSUE TITLE
Internal Architecture Documentation

### ISSUE THREAD

**Issue by djsweet** [djsweet/thorium#4]
Thorium's architecture isn't entirely obvious, and could use non-code documentation.

## `query-tree`

The `query-tree` project already has fairly comprehensive Javadocs. A project-specific README with a high-level overview of how the individual files all fit together, justification for implementation details in QueryTree and QPTrie, and usage examples may be sufficient here.

- [ ] Add subproject specific README with high-level overview, design considerations, and usage examples

## `thorium`

- [ ] Overall theory of operation -- producers, consumers, where QueryTree fits in, where `TranslatorVerticle` and `QueryRouterVerticle` factor into the event pipeline
- [ ] Relationship between `QueryClientSSEServer` and the verticles in `QueryServer.kt`
  Eventually we'll need one for the inevitable WebSocket implementation outlined in #3
- [ ] Documentation of both why and how in `Radix64LowLevelEncoder` and `Radix64HighLevelEncoder`
- [ ] `KeyValueSizeLimits.kt` and the `kvp-byte-budget` sub-command need a thorough explanation -- and a justification.
- [ ] Expectations for future features -- why not a configuration file, why not natively support disjunctions (OR), etc.
- [ ] Roadmap of intended future features
