### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by djsweet** [djsweet/thorium#7]
All builds, tests, and benchmarks are local right now. At least some of these should run in a CI setup, possibly [GitHub Actions](https://docs.github.com/en/actions).

- [x] Automatic builds for all branches
- [x] Automatic tests for all branches
- [x] Figure out if we can run benchmarks in less time, possibly with a 5-10 minute goal

**Comment by djsweet** [comment]
We're now covered on all bases with GitHub Actions!
